<?php

/**
 * Implementation of hook_form_alter().
 */
function nodewords_nodetype_twitter_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_type_form' && isset($form['#node_type'])) {
var_dump($form['nodewords_nodetype']);
//     $form['nodewords_nodetype'] = array(
//       '#type' => 'fieldset',
//       '#title' => t('Meta tags node type'),
//       '#collapsible' => TRUE,
//       '#collapsed' => TRUE,
//     );
    $form['nodewords_nodetype']['nodewords_nodetype_twitter_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Default "title" meta tag for %type', array('%type' => $form['#node_type']->name)),
      '#default_value' => variable_get('nodewords_nodetype_twitter_title_'. $form['#node_type']->type, ''),
      '#size' => 60,
      '#maxlength' => variable_get('nodewords_max_size', 255),
      '#description' => t('Tokens are supported. This keywords will override the global keywords of your site, so please include them here if you need them to appear. Enter a comma separated list of keywords for this page. Avoid duplication of words as this will lower your search engine ranking.'),
    );
var_dump($form['nodewords_nodetype']);
  }
}

/**
 * Implementation of hook_nodewords_tags_alter().
 */
function nodewords_nodetype_twitter_nodewords_tags_alter(&$output_tags, $tag_options) {
  if ($tag_options['type'] == NODEWORDS_TYPE_NODE) {
    // $tag_options['id'] is nodewords-6.12 and above and $tag_options['ids'][0]
    // is nodewords 6.11 and below
    $nid = isset($tag_options['id']) ? $tag_options['id'] : $tag_options['ids'][0];
    $node = node_load($nid);

        var_dump(token_replace('[title]', 'node', $node));
    // Use node-type defaults for this node unless the user specified to use the node's specific values)
    if (is_null($node->nodewords_nodetype_override) || !$node->nodewords_nodetype_override) {
     
      // twitter card
      if ( ( $twitter_title = variable_get('nodewords_nodetype_twitter_card'. $node->type, '') ) !== '' ) {
        $output_tags['twitter:card'] = token_replace($twitter_card, 'node', $node);
      }
      // twitter title
      if ( ( $twitter_title = variable_get('nodewords_nodetype_twitter_title_'. $node->type, '') ) !== '' ) {
        $output_tags['twitter:title'] = token_replace($twitter_title, 'node', $node);
      }
     
var_dump($output_tags);
    }
  }
}

